name: CI/CD Production

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci-base.yml

  deploy-production:
    needs: ci
    uses: ./.github/workflows/deploy-vercel.yml
    with:
      environment: production
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
